# Orion-LD Interface Configuration
orion-ld-if:
  orion-ld:
    domain: http://marketplace-orionld:1026
    path:
      entities: /ngsi-ld/v1/entities
      subscriptions: /ngsi-ld/v1/subscriptions
  api:
    domain: http://marketplace-orionld-adapter:8080
    path:
      subscription: /api/v1/subscribe
      entities: /api/v1/publish
  subscription:
    type: "Subscription"
    notification-endpoint-uri: http://marketplace-blockchain-connector-core:8080/notifications/orion-ld
    entities: >
      ProductOrder
    id-prefix: "urn:ngsi-ld:Subscription:"

# Blockchain Interface Configuration
blockchain-node-if:
  api:
    domain: http://marketplace-dlt-adapter:8080
    path:
      configure-node: /api/v1/configureNode
      publish: /api/v1/publishEvent
      subscribe: /api/v1/subscribe
  subscription:
    active: true
    notification-endpoint-uri: http://marketplace-blockchain-connector-core:8080/notifications/blockchain-node
    event-type: "ProductOffering"
  node:
    rpcAddress: https://red-t.alastria.io/v0/9461d9f4292b41230527d57ee90652a6 #http://52.19.141.129:22000
    userEthereumAddress: "0xb794f5ea0ba39494ce839613fffba74279579268"